"""Remove status column from Payment

Revision ID: 04932cc61ad1
Revises: 139a8012e2f2
Create Date: 2026-01-06 15:55:50.028015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04932cc61ad1'
down_revision = '139a8012e2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
