"""Add request_approval to CustomSticker

Revision ID: 1858e7450cac
Revises: 4a63b2080370
Create Date: 2025-12-19 10:48:03.586412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1858e7450cac'
down_revision = '4a63b2080370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_sticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_approval', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_sticker', schema=None) as batch_op:
        batch_op.drop_column('request_approval')

    # ### end Alembic commands ###
