"""date and time db type name change

Revision ID: 3cb07fa21f13
Revises: 05dafb64e6e0
Create Date: 2026-01-12 11:02:26.664699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb07fa21f13'
down_revision = '05dafb64e6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.String(length=20),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
