"""Added Custom Sticker Model

Revision ID: 583b360a0766
Revises: e1cb65be3234
Create Date: 2025-12-16 10:02:50.222226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583b360a0766'
down_revision = 'e1cb65be3234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_sticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('approval_status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_sticker')
    # ### end Alembic commands ###
