"""add is_custom to sticker

Revision ID: 5c0c2fc2cb4b
Revises: 4fd289d5fcd0
Create Date: 2026-01-09 09:27:21.595938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0c2fc2cb4b'
down_revision = '4fd289d5fcd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_custom', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.drop_column('is_custom')

    # ### end Alembic commands ###
