"""Added stock

Revision ID: 6a23d31b5e44
Revises: 1858e7450cac
Create Date: 2025-12-19 11:02:47.224587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a23d31b5e44'
down_revision = '1858e7450cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))
        batch_op.drop_column('is_custom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_custom', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
