"""is active added to Sticker Model

Revision ID: 789fbbc9e4a2
Revises: 6a23d31b5e44
Create Date: 2025-12-19 13:55:11.928992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789fbbc9e4a2'
down_revision = '6a23d31b5e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
